namespace SunamoLang.SunamoI18N;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



// This class was auto-generated by the StronglyTypedResourceBuilder
// class via a tool like ResGen or Visual Studio.
// To add or remove a member, edit your .ResX file then rerun ResGen
// with the /str option, or rebuild your VS project.
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public class ResourcesDuo {

    private static global::System.Resources.ResourceManager resourceMan;

    private static global::System.Globalization.CultureInfo resourceCulture;

    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    public ResourcesDuo() {
    }

    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    public static global::System.Resources.ResourceManager ResourceManager {
        get {
            if (object.ReferenceEquals(resourceMan, null)) {
                global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SunamoI18N.ResourcesDuo", typeof(ResourcesDuo).Assembly);
                resourceMan = temp;
            }
            return resourceMan;
        }
    }

    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    public static global::System.Globalization.CultureInfo Culture {
        get {
            return resourceCulture;
        }
        set {
            resourceCulture = value;
        }
    }

    public static string Html5BoilerplateEnd {
        get {
            return ResourceManager.GetString("Html5BoilerplateEnd", resourceCulture);
        }
    }

    public static string Html5BoilerplateMiddle {
        get {
            return ResourceManager.GetString("Html5BoilerplateMiddle", resourceCulture);
        }
    }

    public static string Html5BoilerplateStart {
        get {
            return ResourceManager.GetString("Html5BoilerplateStart", resourceCulture);
        }
    }

    public static byte[] sunamo_cs_CZ_min {
        get {
            object obj = ResourceManager.GetObject("sunamo_cs_CZ_min", resourceCulture);
            return ((byte[])(obj));
        }
    }

    public static byte[] sunamo_en_US_min {
        get {
            object obj = ResourceManager.GetObject("sunamo_en_US_min", resourceCulture);
            return ((byte[])(obj));
        }
    }
}
